name: Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: dotnet test
